# NixOS module for Wuling DevOps.
#
# Provides `services.wuling` and wires up:
#   - wuling-api & wuling-migrate as systemd services
#   - Optional nginx static-serve for the frontend
#   - Optional Caddy reverse proxy with auto-TLS
#   - Persistent state directories (repos, ssh host key)
#   - Hardened service options (DynamicUser, ProtectSystem, etc.)
#
# Postgres is intentionally NOT managed here — too many sites already have an
# opinion. Point services.wuling.databaseUrl at whatever you've got.

{ config, lib, pkgs, ... }:

let
  cfg = config.services.wuling;
  inherit (lib) mkIf mkEnableOption mkOption types optional optionalString optionals concatStringsSep;

  # Resolve the flake's packages from the same nixpkgs the host uses.
  # When this module is consumed via `wuling.nixosModules.default`, the
  # wuling flake's overlay injects a `pkgs.wuling-api` / `pkgs.wuling-frontend`
  # attribute. If the user wants to override the package set, they can pass
  # `services.wuling.package = pkgs.something-else`.
  apiPkg = cfg.package;
  migratePkg = cfg.migratePackage;
  frontendDist = cfg.frontend.package;
in
{
  options.services.wuling = {
    enable = mkEnableOption "Wuling DevOps API server";

    package = mkOption {
      type = types.package;
      default = pkgs.wuling-api or (throw "services.wuling.package is unset and pkgs.wuling-api is not in scope — set it explicitly or apply this flake's overlay.");
      defaultText = lib.literalExpression "pkgs.wuling-api";
      description = "wuling-api package. Defaults to the one from this flake.";
    };

    migratePackage = mkOption {
      type = types.package;
      default = pkgs.wuling-migrate or (throw "services.wuling.migratePackage is unset and pkgs.wuling-migrate is not in scope — set it explicitly or apply this flake's overlay.");
      defaultText = lib.literalExpression "pkgs.wuling-migrate";
      description = "wuling-migrate package. Run via ExecStartPre on each restart.";
    };

    domain = mkOption {
      type = types.str;
      example = "devops.example.com";
      description = "Public hostname the service is reachable on (used by the reverse proxy + CORS).";
    };

    httpAddr = mkOption {
      type = types.str;
      default = ":8080";
      description = "Address the API HTTP server binds to. The reverse proxy should target this.";
    };

    sshEnabled = mkOption {
      type = types.bool;
      default = true;
      description = "Enable the embedded Git-over-SSH server.";
    };

    sshAddr = mkOption {
      type = types.str;
      default = ":2222";
      description = "Address the Git-over-SSH server binds to.";
    };

    sshHostKeyFile = mkOption {
      type = types.path;
      default = "/var/lib/wuling/ssh/host_ed25519";
      description = ''
        Path to the SSH host key. Generated by ssh-keygen if missing; keep it
        on persistent storage so it doesn't rotate on every restart.
      '';
    };

    databaseUrl = mkOption {
      type = types.str;
      example = "postgres:///wuling?host=/run/postgresql";
      description = "Postgres DSN. Prefer a Unix socket for same-host setups.";
    };

    jwtSecretFile = mkOption {
      type = types.path;
      description = ''
        Path to an EnvironmentFile (systemd format) whose only line is
        `WULING_JWT_SECRET=<value>`. The value should be a strong random
        string (e.g. `openssl rand -hex 48`). Use sops-nix / agenix to
        inject it; don't world-read this file.
      '';
    };

    repoRoot = mkOption {
      type = types.path;
      default = "/var/lib/wuling/repos";
      description = "Where bare git repositories live. Persistent.";
    };

    extraEnvironment = mkOption {
      type = types.attrsOf types.str;
      default = { };
      description = "Extra WULING_* env vars passed to the service.";
    };

    frontend = {
      enable = mkOption {
        type = types.bool;
        default = true;
        description = "Serve the static frontend bundle with nginx.";
      };
      package = mkOption {
        type = types.package;
        default = pkgs.wuling-frontend or (throw "services.wuling.frontend.package is unset and pkgs.wuling-frontend is not in scope — set it explicitly or apply this flake's overlay.");
        defaultText = lib.literalExpression "pkgs.wuling-frontend";
        description = "wuling-frontend package (the dist/ directory).";
      };
    };

    reverseProxy = mkOption {
      type = types.enum [ "caddy" "nginx" "none" ];
      default = "caddy";
      description = ''
        Which reverse proxy to configure. `caddy` enables services.caddy with
        a virtualHost for {domain}; `nginx` does the same with services.nginx;
        `none` leaves you to wire one up yourself.
      '';
    };
  };

  config = mkIf cfg.enable {
    # ── State directories ────────────────────────────────────────────────
    systemd.tmpfiles.rules = [
      "d ${cfg.repoRoot}                   0750 wuling wuling -"
      "d ${builtins.dirOf (toString cfg.sshHostKeyFile)}  0700 wuling wuling -"
    ];

    users.users.wuling = {
      isSystemUser = true;
      group = "wuling";
      home = "/var/lib/wuling";
      createHome = true;
    };
    users.groups.wuling = { };

    # ── API service ──────────────────────────────────────────────────────
    systemd.services.wuling-api = {
      description = "Wuling DevOps API";
      after = [ "network-online.target" ];
      wants = [ "network-online.target" ];
      wantedBy = [ "multi-user.target" ];

      environment = lib.mkMerge [
        {
          WULING_ENV = "prod";
          WULING_HTTP_ADDR = cfg.httpAddr;
          WULING_HTTP_CORS_ORIGINS = "https://${cfg.domain}";
          WULING_LOG_FORMAT = "json";
          WULING_LOG_LEVEL = "info";
          WULING_DB_DSN = cfg.databaseUrl;
          WULING_REPO_ROOT = toString cfg.repoRoot;
          WULING_SSH_ENABLED = if cfg.sshEnabled then "true" else "false";
          WULING_SSH_ADDR = cfg.sshAddr;
          WULING_SSH_HOST_KEY = toString cfg.sshHostKeyFile;
        }
        cfg.extraEnvironment
      ];

      serviceConfig = {
        Type = "simple";
        # JWT secret is loaded via a tmpfile-style EnvironmentFile that we
        # generate on-the-fly from cfg.jwtSecretFile, so it doesn't end up
        # in /proc/<pid>/environ visible to other users.
        ExecStartPre = [
          # 1. Run DB migrations
          "${migratePkg}/bin/wuling-migrate"
          # 2. Generate SSH host key on first boot
          "${pkgs.bash}/bin/bash -c 'test -f ${cfg.sshHostKeyFile} || ${pkgs.openssh}/bin/ssh-keygen -t ed25519 -N \"\" -f ${cfg.sshHostKeyFile} -C wuling-host'"
        ];
        ExecStart = "${apiPkg}/bin/wuling-api";
        Restart = "on-failure";
        RestartSec = "3s";

        User = "wuling";
        Group = "wuling";
        StateDirectory = "wuling";
        WorkingDirectory = "/var/lib/wuling";

        EnvironmentFile = "-${cfg.jwtSecretFile}";  # contents must be `WULING_JWT_SECRET=<value>`

        # Hardening
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        PrivateDevices = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];
        RestrictNamespaces = true;
        RestrictSUIDSGID = true;
        LockPersonality = true;
        SystemCallArchitectures = "native";
        SystemCallFilter = [ "@system-service" ];
        LimitNOFILE = 65536;

        # The state dirs above need to be writable by wuling. Include the
        # configurable repo and ssh-host-key locations so users who point
        # them outside /var/lib/wuling don't hit EROFS.
        ReadWritePaths = lib.unique [
          "/var/lib/wuling"
          (toString cfg.repoRoot)
          (builtins.dirOf (toString cfg.sshHostKeyFile))
        ];
      };
    };

    # ── Firewall ─────────────────────────────────────────────────────────
    networking.firewall.allowedTCPPorts =
      let
        # Take the substring after the last `:` so "0.0.0.0:2222" works the
        # same as ":2222".
        sshPort = lib.toInt (lib.last (lib.splitString ":" cfg.sshAddr));
      in
      optionals (cfg.reverseProxy != "none") [ 80 443 ]
      ++ optional cfg.sshEnabled sshPort;

    # ── Caddy reverse proxy + static frontend ────────────────────────────
    services.caddy = mkIf (cfg.reverseProxy == "caddy") {
      enable = true;
      virtualHosts.${cfg.domain}.extraConfig = ''
        encode gzip zstd

        @api path /api/* /healthz /version
        reverse_proxy @api 127.0.0.1${cfg.httpAddr}

        @git path_regexp git ^/[^/]+/[^/]+/[^/]+\.git(/|$)
        reverse_proxy @git 127.0.0.1${cfg.httpAddr} {
            flush_interval -1
        }

        ${optionalString cfg.frontend.enable ''
          root * ${frontendDist}
          try_files {path} /index.html
          file_server
        ''}

        header {
            Strict-Transport-Security "max-age=31536000; includeSubDomains; preload"
            X-Content-Type-Options "nosniff"
            Referrer-Policy "strict-origin-when-cross-origin"
        }
      '';
    };

    # ── Nginx alternative ────────────────────────────────────────────────
    services.nginx = mkIf (cfg.reverseProxy == "nginx") {
      enable = true;
      recommendedTlsSettings = true;
      recommendedGzipSettings = true;
      recommendedProxySettings = true;

      virtualHosts.${cfg.domain} = {
        enableACME = true;
        forceSSL = true;

        # Static frontend
        root = mkIf cfg.frontend.enable (toString frontendDist);
        locations."/" = mkIf cfg.frontend.enable {
          tryFiles = "$uri /index.html";
        };

        # REST + healthz
        locations."/api/" = {
          proxyPass = "http://127.0.0.1${cfg.httpAddr}";
        };
        locations."/healthz".proxyPass = "http://127.0.0.1${cfg.httpAddr}";
        locations."/version".proxyPass = "http://127.0.0.1${cfg.httpAddr}";

        # Git smart HTTP — must NOT be buffered; otherwise large packs hang
        locations."~ ^/[^/]+/[^/]+/[^/]+\\.git(/|$)" = {
          proxyPass = "http://127.0.0.1${cfg.httpAddr}";
          extraConfig = ''
            proxy_buffering off;
            proxy_request_buffering off;
            client_max_body_size 1g;
          '';
        };
      };
    };

    security.acme = mkIf (cfg.reverseProxy == "nginx") {
      acceptTerms = true;
      defaults.email = lib.mkDefault "ops@${cfg.domain}";
    };
  };
}
